apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort     # Expuesto al exterior del cluster
  selector:
    app: app        # Coincide con las labels de los Pods
  ports:
    - protocol: TCP
      port: 80        # Puerto que los otros pods usarán para conectarse
      targetPort: 80  # Puerto del contenedor
      nodePort: 30010
